#!/usr/bin/env python
# coding=utf-8

import argparse
from zhedod.dict import open_dict
import sys


def main(raw_args):
    parser = argparse.ArgumentParser(description='Perform dictionary lookups')
    parser.add_argument('text')
    args = parser.parse_args(raw_args)

    text = unicode(args.text, 'utf-8')

    with open_dict() as d:
        while text:
            prefs = d.prefixes(text)
            prefs = sorted(prefs, key=len, reverse=True)
            advance = 1
            if prefs:
                pref = prefs[0]
                for x in d[pref]:
                    print(x)
                advance = len(pref)
            text = text[advance:]
            print "===="




if __name__ == '__main__':
    main(sys.argv[1:])
