#!/usr/bin/env python
# coding=utf-8
# qingfanyi - Chinese to English translation tool
# Copyright (C) 2016 Rohan McGovern <rohan@mcgovern.id.au>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import print_function
import argparse
import qingfanyi.index_builder as builder

import sys


def main(raw_args):
    parser = argparse.ArgumentParser(description='Build index for qingfanyi dictionary')
    parser.add_argument('--dict',
                        default='cedict_1_0_ts_utf-8_mdbg.txt.gz',
                        help='Dictionary file; CEDICT format; text or gzip-compressed')
    args = parser.parse_args(raw_args)
    builder.build(args.dict, logger=print)


if __name__ == '__main__':
    main(sys.argv[1:])
