#!/usr/bin/env python
# coding=utf-8
from __future__ import print_function
import argparse
import qingfanyi.index_builder as builder

import sys


def main(raw_args):
    parser = argparse.ArgumentParser(description='Build index for qingfanyi dictionary')
    parser.add_argument('--dict',
                        default='cedict_1_0_ts_utf-8_mdbg.txt.gz',
                        help='Dictionary file; CEDICT format; text or gzip-compressed')
    args = parser.parse_args(raw_args)
    builder.build(args.dict, logger=print)


if __name__ == '__main__':
    main(sys.argv[1:])
