#!/bin/sh
set -xe

build_srpm(){
  name="$1"
  cfg="$2"
  dist="$3"
  src="$4"

  rm -vf build/$name-*.$dist.src.rpm
  mock --resultdir ./build -r "$cfg" --buildsrpm --spec "$name.spec" --sources "$src"
}

build_rpm(){
  name="$1"
  cfg="$2"
  dist="$3"

  mock --resultdir ./build -r "$cfg" build/$name-*.$dist.src.rpm
}

do_for(){
  cfg="$1"
  dist="$2"
  build_srpm python-marisa-trie "$cfg" "$dist" src/marisa-trie
  build_rpm python-marisa-trie "$cfg" "$dist"
  build_srpm python-ewmh "$cfg" "$dist" src/ewmh
  build_rpm python-ewmh "$cfg" "$dist"
  build_srpm qt-at-spi "$cfg" "$dist" src/qtatspi
  build_rpm qt-at-spi "$cfg" "$dist"
  build_srpm qingfanyi "$cfg" "$dist" src/qingfanyi
  build_rpm qingfanyi "$cfg" "$dist"
}

run(){
  cd "$(dirname "$0")"

  do_for epel-7-x86_64 centos
  do_for fedora-23-x86_64 fc23
}

run

